<?php

namespace Database\Seeders;

use App\Models\Ingredient;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class IngredientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ingredients = [
            'Petto di pollo',
            'Fesa di tacchino',
            'Bresaola',
            'Prosciutto cotto sgrassato',
            'Manzo magro',
            'Carne macinata magra',
            'Uova',
            'Albumi',
            'Tonno al naturale',
            'Salmone',
            'Merluzzo',
            'Nasello',
            'Orata',
            'Branzino',
            'Sgombro',
            'Alici',
            'Gamberi',
            'Polpo',
            'Calamari',
            'Seppie',
            'Sardine',
            'Pesce spada',
            'Yogurt greco 0%',
            'Skyr',
            'Yogurt bianco magro',
            'Yogurt di soia',
            'Latte scremato',
            'Latte parzialmente scremato',
            'Latte di soia',
            'Fiocchi di latte',
            'Ricotta light',
            'Mozzarella light',
            'Feta light',
            'Quark magro',
            'Parmigiano Reggiano',
            'Tofu',
            'Tempeh',
            'Seitan',
            'Edamame',
            'Lenticchie',
            'Ceci',
            'Fagioli cannellini',
            'Fagioli borlotti',
            'Fagioli rossi',
            'Fagioli neri',
            'Piselli',
            'Fave',
            'Lupini',
            'Hummus',
            'Farina di ceci',
            'Proteine whey',
            'Proteine isolate',
            'Proteine vegetali',
            'Proteine di pisello',
            'Proteine di riso',
            'Riso basmati',
            'Riso integrale',
            'Riso venere',
            'Riso jasmine',
            'Riso parboiled',
            'Pasta integrale',
            'Pasta di legumi',
            'Pasta di farro',
            'Pasta di grano duro',
            'Cous cous integrale',
            'Cous cous',
            'Bulgur',
            'Quinoa',
            'Farro',
            'Orzo',
            'Avena',
            'Fiocchi di avena',
            'Crusca di avena',
            'Muesli senza zuccheri',
            'Granola proteica',
            'Pane integrale',
            'Pane di segale',
            'Pane ai cereali',
            'Piadina integrale',
            'Wrap integrale',
            'Gallette di riso',
            'Gallette di mais',
            'Fette biscottate integrali',
            'Patate',
            'Patate dolci',
            'Zucca',
            'Polenta',
            'Mais',
            'Amaranto',
            'Grano saraceno',
            'Zucchine',
            'Melanzane',
            'Peperoni',
            'Pomodori',
            'Pomodorini',
            'Carote',
            'Broccoli',
            'Cavolfiore',
            'Cavolo cappuccio',
            'Cavolo nero',
            'Spinaci',
            'Bietole',
            'Rucola',
            'Lattuga',
            'Insalata mista',
            'Valeriana',
            'Finocchi',
            'Cetrioli',
            'Asparagi',
            'Carciofi',
            'Funghi champignon',
            'Funghi porcini',
            'Cipolle',
            'Cipollotto',
            'Aglio',
            'Porri',
            'Sedano',
            'Radicchio',
            'Barbabietola',
            'Cavoletti di Bruxelles',
            'Fagiolini',
            'Rape',
            'Verza',
            'Cime di rapa',
            'Peperoncino fresco',
            'Mele',
            'Banane',
            'Pere',
            'Arance',
            'Mandarini',
            'Limoni',
            'Lime',
            'Kiwi',
            'Fragole',
            'Mirtilli',
            'Lamponi',
            'More',
            'Frutti di bosco',
            'Ananas',
            'Mango',
            'Pesche',
            'Albicocche',
            'Prugne',
            'Uva',
            'Melone',
            'Anguria',
            'Avocado',
            'Datteri',
            'Fichi',
            'Melagrana',
            'Olio extravergine di oliva',
            'Olio di cocco',
            'Burro di arachidi',
            'Burro di mandorle',
            'Crema di nocciole 100%',
            'Mandorle',
            'Noci',
            'Nocciole',
            'Anacardi',
            'Pistacchi',
            'Pinoli',
            'Semi di chia',
            'Semi di lino',
            'Semi di zucca',
            'Semi di girasole',
            'Semi di sesamo',
            'Tahina',
            'Cocco rapè',
            'Olive nere',
            'Olive verdi',
            'Cacao amaro',
            'Cioccolato fondente 85%',
            'Miele',
            'Sciroppo d\'acero',
            'Eritritolo',
            'Stevia',
            'Cannella',
            'Curcuma',
            'Zenzero',
            'Paprika',
            'Curry',
            'Pepe nero',
            'Sale iodato',
            'Origano',
            'Basilico',
            'Prezzemolo',
            'Rosmarino',
            'Timo',
            'Salvia',
            'Aceto di mele',
            'Aceto balsamico',
            'Salsa di soia a ridotto contenuto di sale',
            'Senape',
            'Passata di pomodoro',
            'Concentrato di pomodoro',
            'Lievito alimentare',
            'Lievito per dolci',
            'Farina integrale',
            'Farina di avena',
            'Farina di mandorle'
        ];

        foreach ($ingredients as $ingredient) {
            $newIngredient = new Ingredient();

            $newIngredient->name = $ingredient;

            $newIngredient->save();

        }
        
    }
}
